### ISSUE TITLE
namespace conflicts with pgjdbc driver

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-postgresql-jdbc#37]
It will be impossible to use both this driver and the pgjdbc driver since the namespaces are the same.

**Comment by adalevinAWS** [comment]
Hi Dave,
Thank you for your feedback. The goal of this driver was to build on the pgjdbc driver to enable applications to take full advantage of high-availability and failover capabilities in Aurora PostgreSQL. Our intention was for it to be drop-in compatible with the pgjdbc driver. We wanted to create less friction for those who currently run the pgjdbc driver and also want to use the AWS driver. We also wanted to reduce friction with any up-streamed changes that might benefit the community. We did not intend to take credit for the community’s work. We apologize it came off that way.

We propose making the following changes and we’d like your feedback:

1. Currently, the AWS Driver can accept connection strings of both protocols jdbc:postgresql:// and jdbc:postgresql:aws://. We could change to only ever accept jdbc:postgresql:aws:// or change the default behavior where a user must explicitly enable the jdbc:postgresql:// protocol if they wanted that to be accepted. 
2. Rather than changing the namespace in the project, we opted to use shading in the Gradle build. We hear from you that this approach is not sufficient. Would refactoring the namespace from “org.postgresql” to “software.aws.rds.jdbc.postgresql” in the files directly versus shading address your concern?

I look forward to your feedback.

Thank you,
Adam Levin 
Product Manager, Aurora PostgreSQL

**Comment by adalevinAWS** [comment]
Thank you for the feedback on these changes. Agreed on the desire to reduce confusion. We’ll work on implementing this.

**Comment by gunnarmorling** [comment]
Hey @adalevinAWS, curious what your thoughts are about an approach where instead of creating a complete fork, you'd work within the PG upstream community towards establishing the right extension points / SPIs, which would then allow you to provide implementations specific for the Aurora use case?

I don't quite know what your requirements are here and what aspects of the upstream driver exactly need customization for this, but if it's feasible, such approach would be quite advantageous. For instance, users of Aurora would benefit from any bug fixes and other improvements done to the upstream driver, the community at large would benefit from any improvements you may do, etc. Did you explore this path?

**Comment by adalevinAWS** [comment]
Yes, we want to explore this, but we want to get the initial changes noted above in place first.

**Comment by davecramer** [comment]
Hey @adalevinAWS this seems to be going in a very strange direction https://github.com/awslabs/aws-postgresql-jdbc/pull/39. How will this driver live in the same JVM as the pgjdbc driver. Since this is not a fork, rather a copy I think it would be wise to repackage under some other namespace...

**Comment by adalevinAWS** [comment]
The Atlas driver uses JAR shading at build time and the PR disables the use of the PostgreSQL protocol and enforces the AWS protocol. Here’s where the shading appears in the code: https://github.com/awslabs/aws-postgresql-jdbc/blob/1b63401d991d31950f434f72f10041ac5afcf688/pgjdbc/build.gradle.kts#L180
This PR allows you to load the community driver and the Atlas driver in the same class path. However, this will not work if you choose to not use our build process. This is a near-term fix.

Longer term, we’d be happy to work on upstreaming changes back into the community driver if there's interest. We’re also exploring the possibility of the plugin approach and how that could work with the community driver.

**Comment by davecramer** [comment]
@adalevinAWS yes, I was made aware of this after I posted this.
